# Host: localhost    Database: 471
# ------------------------------------------------------
# Server version 5.0.51b-community-nt-log

DROP DATABASE IF EXISTS `471`;
CREATE DATABASE `471` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `471`;


DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT (
	AHC			CHAR(9) not null,
    SEX			CHAR(1),
    DOB			DATE not null,
    FName		varchar(25) not null,
    MidIN		char(1),
    LName		varchar(25) not null,
    PName		varchar(25),
    HeadAHC 	CHAR(9),
    StreetName 	varchar(100) not null,
    StreetNum 	varchar(10) not null,
    City 		varchar(10) not null,
    Country		varchar(10) not null,
    PostalCode	varchar(6) not null,
	PRIMARY KEY (AHC),
    FOREIGN KEY (HeadAHC) REFERENCES PATIENT(AHC) 
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
    SIN			CHAR(9) not null,
    OPhone		varchar(14) DEFAULT '4031112222',
    JobType		varchar(20) not null,
    SuperSIN 	CHAR(9),
	DOB			DATE not null,
    FName		varchar(25) not null,
    MidIN		char(1),
    LName		varchar(25) not null,
	PRIMARY KEY (SIN),
    FOREIGN KEY(SuperSIN) REFERENCES EMPLOYEE(SIN)
);

DROP TABLE IF EXISTS PATIENT_PHONE;
CREATE TABLE PATIENT_PHONE (
	AHC			CHAR(9) not null,
    PhoneNum	varchar(14),
    PRIMARY KEY (AHC, PhoneNum),
    CONSTRAINT PXPHONEFK FOREIGN KEY (AHC) REFERENCES PATIENT(AHC) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS NON_MEDICAL_STAFF;
CREATE TABLE NON_MEDICAL_STAFF (
	SIN		CHAR(9) not null,
    PRIMARY KEY (SIN),
    CONSTRAINT NONMEDSTAFFFK FOREIGN KEY (SIN) REFERENCES EMPLOYEE(AHC) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS MEDICAL_STAFF;
CREATE TABLE MEDICAL_STAFF (
	SIN	CHAR(9) not null,
    PRIMARY KEY (SIN),
    CONSTRAINT MEDSTAFFFK FOREIGN KEY (SIN) REFERENCES EMPLOYEE(AHC) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS MEDICAL_STAFF_SPECIALIZATION;
CREATE TABLE MEDICAL_STAFF_SPECIALIZATION (
	SIN	CHAR(9) not null,
    PRIMARY KEY (SIN),
    CONSTRAINT MEDSTAFFSPCFK FOREIGN KEY (SIN) REFERENCES EMPLOYEE(AHC) ON DELETE CASCADE ON UPDATE CASCADE
);





    